# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - about.md
 - experiences.md

footer: 'follow me on <a class="fab fa-github" target="_blank" href="https://github.com/sovannarithcheav">Github</a> or <a target="_blank" href="https://twitter.com/che_sovannarith">twitter</a>'

# style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
theme: jekyll-theme-console
